//add a new item
POST http://localhost:8000/api/item
Content-Type: application/json

{
    "item":"This is lklklk item"
}


###
//lists all items
POST http://localhost:8000/api/items
Content-Type: application/json


###
//update the item with corresponding id
PUT http://localhost:8000/api/item/6465c70d41b7bea78b3b5e2f
Content-Type: application/json

{
    "item": "call me tonight!"
}

###
//delete the item with corresponding id
DELETE  http://localhost:8000/api/item/646490804c4a6161fcbbde10
Content-Type: application/json
